name: Update DNS Rules

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 20 * * *' # 每天 UTC 时间 20:00 (北京时间 04:00) 执行

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set script executable
        run: chmod +x ./scripts/update_rules.sh

      - name: Run update script
        run: ./scripts/update_rules.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add overseas-vps/mosdns/rules/
          # 如果没有文件变动，则不执行commit
          if ! git diff --staged --quiet; then
            git commit -m "chore(rules): Automatic update of DNS rules"
            git push
          else
            echo "No changes to commit."
          fi 